name: birthdays_reminder
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  get_it: ^7.6.7
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  image_picker: ^1.0.7
  json_annotation: ^4.8.1
  auto_route: ^7.8.4
  table_calendar: ^3.0.9
  awesome_notifications: ^0.8.2
  flutter_svg: ^2.0.9
  intl: ^0.18.1
  bloc: ^8.1.3
  yandex_mobileads: ^6.3.0
dev_dependencies:
  auto_route_generator: ^7.3.2
  flutter_test:
    sdk: flutter
  build_runner: null
  json_serializable: ^6.7.1
dependency_overrides:
  crypto: ^3.0.0
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/MontserratAlternates-Medium.ttf
          weight: 500
        - asset: assets/fonts/MontserratAlternates-Medium.ttf
          weight: 400
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
